matrix:
  include:
    - language: node_js
      node_js:
        - 12.13.1
      before_install:
        - cd stellaris-configuration-jsonifier
      install:
        - npm install 
      script:
        - npm test